## Exp-1:Linear Algebra in Python3 &amp; associated operations

In [21]:
import numpy as np

In [22]:
#Advantage of numpy library over lists
#In list we cannot define 2D array or 3D array

list=[1,2,3,4]
print(list)

#To create an array we use np.array funcion
#Creating 1D array
print(np.array([1,2,3,4]))

#Creating 2D array
print(np.array([[[1,2,3,4],
               [5,6,7,8]]]))

#Creating 3D array
print(np.array([[[1,2,3,4],
                [5,6,7,8],
                [9,10,11,12]]]))





[1, 2, 3, 4]
[1 2 3 4]
[[[1 2 3 4]
  [5 6 7 8]]]
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]


In [23]:
# Type of array

a=np.array([1,2,3,4])
b=np.array([[1,2,3],
           [4,5,6]])
c=np.array([[[1,2,3,4],
           [5,6,7,8],
           [9,10,11,12]]])
type(a)
type(b)
type(c)

numpy.ndarray

In [24]:
#Size of array: total number of elements
print(np.size(a))
print(np.size(b))
print(np.size(c))

4
6
12


In [25]:
#shape of the array: gives the number of rows and columns

print(a.shape) #no of columns
print(b.shape) #no ofrows, columns
print(c.shape) # no of array,no of rows, no columns


(4,)
(2, 3)
(1, 3, 4)


In [26]:
#dtype: type of data present in the array
print(a.dtype)
print(b.dtype)
print(c.dtype)

int32
int32
int32


In [27]:
#changing the data type of the elements
d=np.array([1.2,3.4])
print(d.dtype)


float64


In [31]:
#Transpose function
print(b.transpose()) #doesnt work for 1D array


[[1 4]
 [2 5]
 [3 6]]


In [32]:
#np.empty((rows,columns),data type)

np.empty((4,4),dtype=int) #randomly generated array of given data type and size

array([[      0,       0,       0,       0],
       [      0,       0,       0,       0],
       [      0,       0,    1656,       0],
       [      0, 6029410,       0, 3014754]])

In [34]:
#np.ones((rows,columns),data type)
np.ones((2,2),dtype=float) #generates an array of ones of given data type and size



array([[1., 1.],
       [1., 1.]])

In [36]:
#np.zeros((rows,columns),data type)
np.zeros((2,2),dtype=int) #generates an array of zeroes of given data type and size

array([[0, 0],
       [0, 0]])

In [38]:
print(np.zeros((2,2),dtype=str))
print(np.ones((4,4),dtype=str))
 

[['' '']
 ['' '']]
[['1' '1' '1' '1']
 ['1' '1' '1' '1']
 ['1' '1' '1' '1']
 ['1' '1' '1' '1']]


In [39]:
print(np.zeros((2,2),dtype=bool))
print(np.ones((4,4),dtype=bool))

[[False False]
 [False False]]
[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]


In [40]:
#np.arange(start,stop,step)

a=np.arange(1,20) #1 to 20 and skips 20 with the step as default 1
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [41]:
b=np.arange(1,20,2) 
print(b)

[ 1  3  5  7  9 11 13 15 17 19]


In [48]:
#arr.reshape((rows,columns))
b=np.array([[1,2,3,4],
           [5,6,7,8]])   #only when the product is the same
print(b.reshape(4,2))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
