In [1]:
import numpy as np

# Exercise 1: Matrix Addition
- Write a function that takes two 2D NumPy arrays as input and returns their sum. Make sure to check if the matrices have the same dimensions before performing the addition.

In [2]:
def matrix_addition(matrix1,matrix2): #declaring a function matrix_addition()
    sum=matrix1+matrix2
    return sum

a=[[1,2],[3,4]]  #nested list-1
b=[[5,6],[7,8]]  #nested list-2

matrix1=np.array(a)  #declaring first matrix
matrix2=np.array(b)  #declaring second matrix 
if matrix1.shape==matrix2.shape:          # matrix.shape gives the size of the matrix and comparing the size two matrices
    print("The sum of two matrices is:")
    print(matrix_addition(matrix1,matrix2))
else:
    print("Enter two matrices of the same order")
    

The sum of two matrices is:
[[ 6  8]
 [10 12]]


#  Exercise 2: Matrix Subtraction
- Write a function that takes two 2D NumPy arrays as input and returns their difference. Check if the matrices have the same dimensions before performing the subtraction.

In [3]:
def matrix_subtraction(matrix1,matrix2): #declaring function matrix_subtraction()
    sub=matrix1-matrix2
    return sub

if matrix1.shape==matrix2.shape:  #comparing the size of the two matrices
    print("The difference between the matrices is:")
    print(matrix_subtraction(matrix1,matrix2))
else:
    print("Enter two matrices of the same order")
    

The difference between the matrices is:
[[-4 -4]
 [-4 -4]]


# Exercise 3: Matrix Transpose
- Write a function that takes a 2D NumPy array as input and returns its transpose (switching rows with columns).


In [4]:
def matrix_transpose(matrix1):#declaring the function matrix_transpose 
    transpose=np.transpose(matrix1)
    return transpose

print("The transpose of the matrix is")
print(matrix_transpose(matrix1))

    

The transpose of the matrix is
[[1 3]
 [2 4]]


# Exercise 4: Identity Matrix
- Write a function that takes an integer n as input and returns an n x n identity matrix, i.e., a square matrix with 1's on the main diagonal and 0's elsewhere.


In [5]:
def matrix_identity(n): #declaring the function matrix_identity()
    identity=(np.eye((n),dtype=int)) #dtype=int: changing data type to integer
    return identity

n=int(input("Enter the order of the identity matrix:")) #user input for the order of matrix
print("The identity matrix of order",n,"is")
print(matrix_identity(n))


Enter the order of the identity matrix:5
The identity matrix of order 5 is
[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


# Exercise 5: Eigenvalues and Eigenvectors
- Write a function that takes a 2D NumPy array as input and returns the eigenvalues and corresponding eigenvectors of the matrix.


In [6]:
def matrix_eigenvalues_eigenvectors(matrix1): #declaring function matrix_eigenvalues_eigenvectors()
    eigenvalues,eigenvectors=np.linalg.eig(matrix1) #finding the eigen values and vectors
    return eigenvalues,eigenvectors

eigenvalues,eigenvectors=matrix_eigenvalues_eigenvectors(matrix1)
print("Eigenvalues") #Printing eigen values
print(eigenvalues)
print("Eigenvectors") #Printing eigen vectors
print(eigenvectors)

Eigenvalues
[-0.37228132  5.37228132]
Eigenvectors
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


# Norm Exercises

# Exercise 6: Vector Norm
- Write a function that takes a 1D NumPy array as input and returns its L2 norm, also known as the Euclidean norm.


In [7]:
def Euclidean_norm(array): #defining a function Euclidean_norm()
    L2_norm=np.linalg.norm(array,ord=2) #finding Eucliean norm
    return L2_norm

list=[1,2,3]
array=np.array(list) #initialising 1D array
print("The Euclidean/L2 norm is")
print(Euclidean_norm(array))


The Euclidean/L2 norm is
3.7416573867739413


# Exercise 7: Matrix Norm
- Write a function that takes a 2D NumPy array as input and returns its Frobenius norm, which is the square root of the sum of squares of all elements in the matrix.


In [8]:
def Frobenius_norm(array): # Declaring a function Frobenius_norm()
    matrix_norm=np.linalg.norm(array,ord=2) # Frobenius norm is also called as the Euclidean norm
    return matrix_norm

list=[4,5,6]
array=np.array(list) # declaring a 1D array
print("The Forbenius norm is")
print(Frobenius_norm(array))


The Forbenius norm is
8.774964387392123


# Exercise 8: Normalize a Vector
- Write a function that takes a 1D NumPy array as input and returns its normalized version, i.e., a vector with the same direction but unit length.


In [9]:
def Normalise_vector(arr):#declaring a function Normalise_vector()
    L2_norm=np.linalg.norm(arr,ord=2) #finding the Euclidean norm
    normalise_vector=arr/L2_norm # normalize vector=vector/Euclidean norm
    return normalise_vector
    
arr=np.array([1,2,3,4]) # initialising a 1D array
print("The normalised vector is")
print(Normalise_vector(arr))



The normalised vector is
[0.18257419 0.36514837 0.54772256 0.73029674]


# Exercise 9: Condition Number of a Matrix
- Write a function that takes a 2D NumPy array as input and returns its condition number, which indicates the sensitivity of the matrix to changes in the input.


In [10]:
def matrix_conditional(array): # declaring a function matrix_conditional()
    cond=np.linalg.cond(array) #finding the conditional number
    return cond

array=np.array([[6,7],[8,9]]) # intialising a 2D array
print("The Condition number is")
print(matrix_conditional(array))


The Condition number is
114.99130369020982


# Exercise 10: Calculate Angle Between Vectors
- Write a function that takes two 1D NumPy arrays as input and returns the angle between them.

In [11]:
def angle(array1,array2):# declaring the function angle()
    dot_product=np.dot(array1,array2) # finding the dot_product
    magnitude=np.linalg.norm(array1,ord=2)*np.linalg.norm(array2,ord=2) #finding the magnitude using L2 norm
    cosine_angle=dot_product/magnitude #finding angle using cosine=dot_product/magnitude
    return cosine_angle

array1=np.array([1,2,3]) #declaring array1
array2=np.array([4,5,6]) #declaring array2
print("The angle between two vectors is")
print(angle(array1,array2))




The angle between two vectors is
0.9746318461970762
