### Exp-9: Introduction to text analytics- K-Nearest Neighbours for sentiment analysis

 - (a) Sentiment analysis for Twitter data.
 - (b) Sentiment analysis for Reddit data.

In [2]:
import pandas as pd
import numpy as np
import nltk, warnings,string
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
warnings.filterwarnings('ignore')
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score
from sklearn.neighbors import KNeighborsClassifier
from sklearn.feature_extraction.text import TfidfVectorizer #Term Frequency Inverse Document Frequency
from sklearn.model_selection import train_test_split

### Twitter Data

In [3]:
# Reading the dataframe using pandas
df=pd.read_csv('D:\SEM 3\Python for Data Science\Twitter_Data.csv')

In [4]:
df

clean_text  category
0       when modi promised “minimum government maximum...      -1.0
1       talk all the nonsense and continue all the dra...       0.0
2       what did just say vote for modi  welcome bjp t...       1.0
3       asking his supporters prefix chowkidar their n...       1.0
4       answer who among these the most powerful world...       1.0
...                                                   ...       ...
162975  why these 456 crores paid neerav modi not reco...      -1.0
162976  dear rss terrorist payal gawar what about modi...      -1.0
162977  did you cover her interaction forum where she ...       0.0
162978  there big project came into india modi dream p...       0.0
162979  have you ever listen about like gurukul where ...       1.0

[162980 rows x 2 columns]

In [5]:
df.shape

(162980, 2)

In [6]:
df.head()

clean_text  category
0  when modi promised “minimum government maximum...      -1.0
1  talk all the nonsense and continue all the dra...       0.0
2  what did just say vote for modi  welcome bjp t...       1.0
3  asking his supporters prefix chowkidar their n...       1.0
4  answer who among these the most powerful world...       1.0

In [7]:
df.iloc[:5,:]

clean_text  category
0  when modi promised “minimum government maximum...      -1.0
1  talk all the nonsense and continue all the dra...       0.0
2  what did just say vote for modi  welcome bjp t...       1.0
3  asking his supporters prefix chowkidar their n...       1.0
4  answer who among these the most powerful world...       1.0

In [8]:
df=df.iloc[:100000,:]

In [9]:
df

clean_text  category
0      when modi promised “minimum government maximum...      -1.0
1      talk all the nonsense and continue all the dra...       0.0
2      what did just say vote for modi  welcome bjp t...       1.0
3      asking his supporters prefix chowkidar their n...       1.0
4      answer who among these the most powerful world...       1.0
...                                                  ...       ...
99995  only modi theres question compare freebies wit...       0.0
99996  modi disgrace always people who have expectati...       1.0
99997                           why want vote for modi         0.0
99998  why didnt people say this intolerance all beca...       0.0
99999  modi body language has change lot seems like f...       0.0

[100000 rows x 2 columns]

In [10]:
df.dropna(inplace=True)

In [11]:
df.isna().sum()

clean_text    0
category      0
dtype: int64

In [12]:
df['category'].replace([-1.0,0,1.0],['Negative','Neutral','Positive'],inplace=True)

In [13]:
df

clean_text  category
0      when modi promised “minimum government maximum...  Negative
1      talk all the nonsense and continue all the dra...   Neutral
2      what did just say vote for modi  welcome bjp t...  Positive
3      asking his supporters prefix chowkidar their n...  Positive
4      answer who among these the most powerful world...  Positive
...                                                  ...       ...
99995  only modi theres question compare freebies wit...   Neutral
99996  modi disgrace always people who have expectati...  Positive
99997                           why want vote for modi     Neutral
99998  why didnt people say this intolerance all beca...   Neutral
99999  modi body language has change lot seems like f...   Neutral

[99999 rows x 2 columns]

In [14]:
X=df['clean_text']
y=df['category']

In [15]:
X

0        when modi promised “minimum government maximum...
1        talk all the nonsense and continue all the dra...
2        what did just say vote for modi  welcome bjp t...
3        asking his supporters prefix chowkidar their n...
4        answer who among these the most powerful world...
                               ...                        
99995    only modi theres question compare freebies wit...
99996    modi disgrace always people who have expectati...
99997                             why want vote for modi  
99998    why didnt people say this intolerance all beca...
99999    modi body language has change lot seems like f...
Name: clean_text, Length: 99999, dtype: object

In [16]:
y

0        Negative
1         Neutral
2        Positive
3        Positive
4        Positive
           ...   
99995     Neutral
99996    Positive
99997     Neutral
99998     Neutral
99999     Neutral
Name: category, Length: 99999, dtype: object

In [17]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=42)

In [18]:
tfidf=TfidfVectorizer()
X_train_vect=tfidf.fit_transform(X_train)
X_test_vect=tfidf.transform(X_test)

In [19]:
knn=KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train_vect,y_train)

KNeighborsClassifier()

In [20]:
knn_pred=knn.predict(X_test_vect)
print(confusion_matrix(y_test,knn_pred))
print(classification_report(y_test,knn_pred))
accuracy=accuracy_score(y_test,knn_pred)

[[  421  6129    30]
 [   21  9922   129]
 [   81 11875  1392]]
              precision    recall  f1-score   support

    Negative       0.80      0.06      0.12      6580
     Neutral       0.36      0.99      0.52     10072
    Positive       0.90      0.10      0.19     13348

    accuracy                           0.39     30000
   macro avg       0.69      0.38      0.28     30000
weighted avg       0.70      0.39      0.28     30000



In [40]:
accuracy

0.39116666666666666

### Reddit Data

In [21]:
df1=pd.read_csv('D:\SEM 3\Python for Data Science\Reddit_Data.csv')

In [22]:
df1

clean_comment  category
0       family mormon have never tried explain them t...         1
1      buddhism has very much lot compatible with chr...         1
2      seriously don say thing first all they won get...        -1
3      what you have learned yours and only yours wha...         0
4      for your own benefit you may want read living ...         1
...                                                  ...       ...
37244                                              jesus         0
37245  kya bhai pure saal chutiya banaya modi aur jab...         1
37246              downvote karna tha par upvote hogaya          0
37247                                         haha nice          1
37248             facebook itself now working bjp’ cell          0

[37249 rows x 2 columns]

In [23]:
df1.shape

(37249, 2)

In [25]:
df1.isna().sum()

clean_comment    100
category           0
dtype: int64

In [26]:
df1.dropna(inplace=True)

In [27]:
df1

clean_comment  category
0       family mormon have never tried explain them t...         1
1      buddhism has very much lot compatible with chr...         1
2      seriously don say thing first all they won get...        -1
3      what you have learned yours and only yours wha...         0
4      for your own benefit you may want read living ...         1
...                                                  ...       ...
37244                                              jesus         0
37245  kya bhai pure saal chutiya banaya modi aur jab...         1
37246              downvote karna tha par upvote hogaya          0
37247                                         haha nice          1
37248             facebook itself now working bjp’ cell          0

[37149 rows x 2 columns]

In [29]:
df1['category'].replace([-1,0,1],['Negative','Neutral','Positive'],inplace=True)

In [30]:
df1

clean_comment  category
0       family mormon have never tried explain them t...  Positive
1      buddhism has very much lot compatible with chr...  Positive
2      seriously don say thing first all they won get...  Negative
3      what you have learned yours and only yours wha...   Neutral
4      for your own benefit you may want read living ...  Positive
...                                                  ...       ...
37244                                              jesus   Neutral
37245  kya bhai pure saal chutiya banaya modi aur jab...  Positive
37246              downvote karna tha par upvote hogaya    Neutral
37247                                         haha nice   Positive
37248             facebook itself now working bjp’ cell    Neutral

[37149 rows x 2 columns]

In [31]:
X1=df['clean_text']
y1=df['category']

In [34]:
X1_train,X1_test,y1_train,y1_test=train_test_split(X1,y1,test_size=0.3,random_state=42)

In [36]:
tfidf1=TfidfVectorizer()
X_train_vect1=tfidf.fit_transform(X1_train)
X_test_vect1=tfidf.transform(X1_test)

In [38]:
knn=KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train_vect1,y1_train)

KNeighborsClassifier()

In [39]:
knn_pred1=knn.predict(X_test_vect1)
print(confusion_matrix(y1_test,knn_pred1))
print(classification_report(y1_test,knn_pred1))
accuracy=accuracy_score(y1_test,knn_pred1)

[[  421  6129    30]
 [   21  9922   129]
 [   81 11875  1392]]
              precision    recall  f1-score   support

    Negative       0.80      0.06      0.12      6580
     Neutral       0.36      0.99      0.52     10072
    Positive       0.90      0.10      0.19     13348

    accuracy                           0.39     30000
   macro avg       0.69      0.38      0.28     30000
weighted avg       0.70      0.39      0.28     30000

